export const shopCategories = [
  { value: "automotive", label: "Automotive & Accessories" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "pet", label: "Pet Supplies & Services" },
  { value: "medical", label: "Medical & Pharmacy" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "florist", label: "Florists & Gift Shops" },
  { value: "baby", label: "Baby & Kids Store" },
  { value: "art", label: "Art & Craft Supplies" },
  { value: "music", label: "Music Instruments & Stores" },
  { value: "technology", label: "Software & Technology Services" },
  { value: "garden", label: "Garden & Outdoor Equipment" },
  { value: "bakery", label: "Bakery & Confectionery" },
  { value: "optical", label: "Optical & Eyewear" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "home-kitchen", label: "Home & Kitchen" },
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "footwear", label: "Footwear" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health & Wellness" },
  { value: "appliances", label: "Home Appliances" },
  { value: "furniture", label: "Furniture & Decor" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "food-beverages", label: "Food & Beverages" },
  { value: "crafts-hobbies", label: "Crafts & Hobbies" },
  { value: "office-supplies", label: "Office Supplies" },
  { value: "travel-luggage", label: "Travel & Luggage" },
  { value: "gifts", label: "Gifts & Novelties" },
  { value: "industrial", label: "Industrial & Scientific" },
  { value: "outdoor-recreation", label: "Outdoor Recreation" },
  { value: "collectables", label: "Collectibles & Memorabilia" },
];